[versions]
agp = "9.3.0"
coreKtx = "1.12.0"
activity = "1.8.2"
kotlin = "2.2.10"
appcompat = "1.6.1"
appProjected = "1.4.0"
appAutomotive = "1.7.0"
app = "1.4.0"
junit = "4.13.2"
bouncycastle = "1.79"
jmdns = "3.6.3"
desugarJdkLibs = "2.1.5"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-app-projected = { group = "androidx.car.app", name = "app-projected", version.ref = "appProjected" }
androidx-app-automotive = { group = "androidx.car.app", name = "app-automotive", version.ref = "appAutomotive" }
androidx-app = { group = "androidx.car.app", name = "app", version.ref = "app" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
bouncycastle = { group = "org.bouncycastle", name = "bcprov-jdk18on", version.ref = "bouncycastle" }
jmdns = { group = "org.jmdns", name = "jmdns", version.ref = "jmdns" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
